os:
    - osx
sudo: required
osx_image: beta-xcode6.1
python:
    - '2.7'

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pyenv install 2.7.12 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pyenv global 2.7.12 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo python --version ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo python -m pip install -U pip setuptools ; fi

install:
    - sudo pip install -r requirements/dev-requirements.txt

script: tox
