os:
    - osx
osx_image: beta-xcode6.1
python:
    - '2.7'

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi

install:
    - pip install -r requirements/dev-requirements.txt

script: tox
