language: generic
os: osx
osx_image: beta-xcode6.2

before_install: |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pyenv install --list | grep "2.7" ;
      PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 2.7.9 ;
      pyenv global 2.7.9 ;
      pyenv rehash ;
      export PYTHON=`pyenv which python` ;
    fi

install:
    - $PYTHON -m pip install -r requirements/dev-requirements.txt

script: |
    $PYTHON --version ;
    $PYTHON -m tox ;
    $PYTHON build.py ;
