language: generic
os: osx
sudo: required
osx_image: beta-xcode6.2
python:
    - '2.7'

before_install: |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pyenv install --list | grep "2.7" ;
      pyenv install 2.7.9 ;
      pyenv global 2.7.9 ;
      export PYTHON=`pyenv which python` ;
      which python ;
      $PYTHON --version ;
      wget -c https://bootstrap.pypa.io/get-pip.py ;
      $PYTHON get-pip.py ;
      $PYTHON -m pip install -U pip setuptools ;
    fi

install:
    - $PYTHON -m pip install -r requirements/dev-requirements.txt

script: |
    which tox ;
    $PYTHON --version
    $PYTHON -m tox
    $PYTHON build.py
