language: generic
os: osx
sudo: required
osx_image: beta-xcode6.2
python:
    - '2.7'

before_install: |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pyenv install --list | grep "2.7" ;
      pyenv install 2.7.9 ;
      pyenv global 2.7.9 ;
      export PYTHON=`pyenv which python` ;
      which python ;
      python --version ;
      wget -C https://bootstrap.pypa.io/get-pip.py ;
      python get-pip.py ;
      python -m pip install -U pip setuptools ;
    fi

install:
    - python -m pip install -r requirements/dev-requirements.txt

script: which tox && which python && python --version && tox
