os:
    - osx
sudo: required
osx_image: beta-xcode6.1
python:
    - '2.7'

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -m pip install -U pip ; fi

install:
    - pip install -r requirements/dev-requirements.txt

script: tox
