version: 0.2.2 build {build}
install:
- cmd: python.exe -m pip install -r requirements\dev-requirements.txt
build_script:
- cmd: python build.py
test_script:
- cmd: python -m tox
artifacts:
- path: dist\KeyCounter.exe
  name: KeyCounter.exe
