#!/bin/bash
# From https://git.io/vP4Pw
mkdir createICNS.cache
ls | egrep "\.jpg$|\.jpeg$|\.png$|\.tiff$|\.pdf$|\.gif$|\.jp2$|\.svg$" >> createICNS.cache/filelist.txt
while read line
do
	fileName=$(echo $line)
	prefix=${fileName%.*}
	postfix=${fileName##*.}
	echo $prefix
	echo $postfix
	mkdir "${prefix}".iconset
	if [[ $postfix == 'svg' ]]
		then
		qlmanage -z -t -s 1024 -o ./createICNS.cache "$fileName"
		fileName=createICNS.cache/${fileName}.png
	fi
	echo $fileName
	sips -z 16 16 "$fileName" --out "${prefix}".iconset/icon_16x16.png
	sips -z 32 32 "$fileName" --out "${prefix}".iconset/icon_16x16@2x.png
	cp "${prefix}".iconset/icon_16x16@2x.png "${prefix}".iconset/icon_32x32.png
	sips -z 64 64 "$fileName" --out "${prefix}".iconset/icon_32x32@2x.png
	sips -z 128 128 "$fileName" --out "${prefix}".iconset/icon_128x128.png
	sips -z 256 256 "$fileName" --out "${prefix}".iconset/icon_128x128@2x.png
	cp "${prefix}".iconset/icon_128x128@2x.png "${prefix}".iconset/icon_256x256.png
	sips -z 512 512 "$fileName" --out "${prefix}".iconset/icon_256x256@2x.png
	cp "${prefix}".iconset/icon_256x256@2x.png "${prefix}".iconset/icon_512x512.png
	sips -z 1024 1024 "$fileName" --out "${prefix}".iconset/icon_512x512@2x.png
	iconutil -c icns "${prefix}".iconset
	rm -R "${prefix}".iconset
done < createICNS.cache/filelist.txt
rm -rf createICNS.cache
